/**
 * The Privacy Policy and the Terms & Conditions, as application content.
 *
 * SOURCE. Both documents are transcribed verbatim from Swachham's own Word
 * document ("SOFT WARE MP SIR TYPING.docx"). This is legal text: every word
 * below is the word from that file. Nothing here is written, summarised,
 * paraphrased or corrected -- the source's own spellings, capitalisation and
 * punctuation are kept as they are, because changing them changes what the
 * company has undertaken.
 *
 * The document contains two parts, and they map one-to-one onto the two
 * screens: the "TERMS & CONDITIONS" part (Terms of Service through Section 24,
 * including its own PRIVACY: and PROMOTIONS subsections) and the standalone
 * "Privacy Policy" part that follows it. Where the two overlap, the overlap is
 * the source's; removing it would be editing the document.
 *
 * TO UPDATE. Re-transcribe from the new source document, keeping its order and
 * its wording: a `heading` per titled or numbered section, a `subheading` for a
 * nested clause, a `paragraph` per paragraph, a `bullet` per bulleted item.
 * Set `lastUpdated` if the source carries a revision date -- this one does not.
 *
 * The renderer (`screens/legal/LegalDocumentScreen`) owns all layout, so
 * nothing here needs to concern itself with spacing or type.
 */

export type LegalBlock =
  | { type: 'heading'; text: string }
  /** A smaller heading beneath a `heading`, for nested clauses. */
  | { type: 'subheading'; text: string }
  | { type: 'paragraph'; text: string }
  | { type: 'bullet'; text: string };

export interface LegalDocument {
  /** Shown in the header, e.g. "Privacy Policy". */
  title: string;
  /** The revision date printed on the source document, when it has one. */
  lastUpdated?: string;
  blocks: LegalBlock[];
}

/**
 * PRIVACY POLICY — the standalone policy from the source document.
 */
export const PRIVACY_POLICY: LegalDocument = {
  title: 'Privacy Policy',
  blocks: [
    { type: "heading", text: "PERSONAL INFORMATION" },
    { type: "paragraph", text: "SWACHHAM. is the licensed owner of the brand SWACHHAM and the website www.swachham.co.in (\"The Site\")." },
    { type: "paragraph", text: "SWACHHAM. respects your privacy. This Privacy Policy provides succinctly the manner your data is collected and used by SWACHHAM. on the Site. As a visitor to the Site/ Customer you are advised to please read the Privacy Policy carefully. By accessing the services provided by the Site you agree to the collection and use of your data by SWACHHAM. in the manner provided in this Privacy Policy." },
    { type: "heading", text: "WHAT INFORMATION IS, OR MAY BE, COLLECTED FORM YOU?" },
    { type: "paragraph", text: "As part of the registration process on the Site, SWACHHAM. may collect the following personally identifiable information about you: Name including first and last name, alternate email address, mobile phone number and contact details, Postal code, Demographic profile (like your age, gender, occupation, education, address etc.) and information about the pages on the site you visit/access, the links you click on the site, the number of times you access the page and any such browsing information." },
    { type: "heading", text: "HOW DO WE COLLECT THE INFORMATION?" },
    { type: "paragraph", text: "SWACHHAM. wilI collect personally identifiable information about you only as part of a voluntary registration process, online survey or any combination thereof. The Site may contain links to other Web sites. SWACHHAM. is not responsible for the privacy practices of such Web sites which it does not own, manage or control. The Site and third-party vendors, including Google, use first party cookies (such as the Google Analytics cookie) and third-party cookies (such as the DoubleClick cookie) together to inform, optimize, and serve ads based on someone's past visits to the Site" },
    { type: "heading", text: "WITH WHOM YOUR INFORMATION WILL BE SHARED?" },
    { type: "paragraph", text: "SWACHHAM. wilI not use your financial information for any purpose other than to complete a transaction with you. SWACHHAM. does not rent, sell or share your personal information and will not disclose any of your personally identifiable information to third parties. In cases where it has your permission to provide products or services you've requested, and such information is necessary to provide these products or services the information may be shared with SWACHHAM.'s business associates and partners. SWACHHAM. may, however, share consumer information on an aggregate with its partners or third parties where it deems necessary. In addition, SWACHHAM. may use this information for promotional offers, to help investigate, prevent or take action regarding unlawful and illegal activities, suspected fraud, potential threat to the safety or security of any person, violations of the Site's terms of use or to defend against legal claims; special circumstances such as compliance with subpoenas, court orders, requests/order from legal authorities or law enforcement agencies requiring such disclosure." },
    { type: "heading", text: "WHAT CHOICE ARE AVAILABLE TO YOU REGARDING COLLECTION, USE AND DISTRIBUTION OF YOUR INFORMATION?" },
    { type: "paragraph", text: "To protect against the loss, misuse and alteration of the information under its control, SWACHHAM. has in place appropriate physical, electronic and managerial procedures. For example, SWACHHAM. servers are accessible only to authorized personnel and your information is shared with employees and authorised personnel on a need to know basis to complete the transaction anneed-to-know the services requested by you. Although SWACHHAM. will endeavour to safeguard the confidentiality of your personally identifiable information, transmissions made by means of the Internet cannot be made absolutely secure. By using this site, you agree that SWACHHAM. will have no liability for disclosure of your information due to errors in transmission or unauthorized acts of third parties." },
    { type: "heading", text: "WHY IS LOCATION COLLECTED? HOW IS IT USED?" },
    { type: "paragraph", text: "We use Google Route Optimization API which is a routing algorithm for generating pickup & delivery routes for last mile delivery to the customers. These routes are then downloaded on our delivery app to do the deliveries and Google Route Optimization API on the phone used by riders helps us track the location of the rider. Locus needs to know the path being followed by the rider. Location information of the rider will be used to send relevant updates to the end customer." },
    { type: "heading", text: "HOW ARE YOUR LOCATION DETAILS COLLECTED?" },
    { type: "paragraph", text: "Your location details are collected using a third-party library or google play services based on configurations." },
    { type: "heading", text: "HOW CAN YOU CORRECT INACCURACIES IN THE INFORMATION?" },
    { type: "paragraph", text: "To correct or update any information you have provided, the site allows you to do it online. In the event of loss of access details, you can send an email to : info@swachham.co.in" },
    { type: "heading", text: "POLICY UPDATES" },
    { type: "paragraph", text: "SWACHHAM. reserves the right to change or update this policy at any time. Such changes shall be effective immediately upon posting to the Site." },
    { type: "heading", text: "CONSUMER APP" },
    { type: "subheading", text: "Data retention" },
    { type: "paragraph", text: "SWACHHAM retain personal information only for as long as necessary to provide services, maintain customer accounts, process orders, comply with legal obligations, resolve disputes, prevent fraud, and enforce our agreements." },
    { type: "paragraph", text: "Customer account information, order history, transaction records, payment records, and operational data are retained while the account remains active and for such additional period as may be regulatory requirements, taxation obligation, audit requirements, taxation obligation, audit requirements, and legitimate business purposes." },
    { type: "paragraph", text: "When personal information is no longer required for these purposes, it will be permanently deleted, anonymized, or securely destroyed using industry-standard security practices." },
    { type: "subheading", text: "Data deletion" },
    { type: "paragraph", text: "Customers may request deletion of their personal information and account data at any time by contacting our support team at info@swachham.co.in" },
    { type: "paragraph", text: "Upon receiving and verifying a valid deletion request, SWACHHAM. will delete or anonymize the customer's personal information from its active systems." },
    { type: "paragraph", text: "Certain information may be retained where required by applicable law, regulatory obligations, taxation requirements, audit requirements, fraud prevention purposes, dispute resolution processes, or other legitimate legal obligations. Such information will be retained only for the period required and will be securely deleted thereafter." },
    { type: "paragraph", text: "For account deletion or personal data deletion requests, please contact:" },
    { type: "paragraph", text: "Email: info@swachham.co.in" },
    { type: "heading", text: "DELIVERY PARTNER APP:" },
    { type: "subheading", text: "Data usage" },
    { type: "paragraph", text: "This application is intended exclusively for authorized delivery partners, employees, and operational personnel of SWACHHAM. and is not intended for use by the general public." },
    { type: "paragraph", text: "The application collects information such as employee details, device information, and location data solely for operational purposes, including route optimization, order assignment, pickup and delivery tracking, attendance verification, service quality monitoring, customer notifications, fraud prevention, and operational accountability." },
    { type: "paragraph", text: "Location information may be collected while the delivery partner is actively performing assigned pickup or delivery tasks. This information is used to monitor route progress, improve delivery efficiency, provide accurate delivery status updates to customers, verify task completion, and support operational management." },
    { type: "subheading", text: "Data retention" },
    { type: "paragraph", text: "Delivery partner information, operational records, attendance records, delivery history, device-related information, and location records are retained only for as long as necessary to support business operations, customer service, auditing, compliance requirements, dispute resolution, fraud prevention, and legal obligations." },
    { type: "paragraph", text: "When such information is no longer required for these purposes, it will be permanently deleted, anonymized, or securely destroyed using industry-standard security practices." },
    { type: "heading", text: "HOW DO WE COLLECT THE INFORMATION?" },
    { type: "paragraph", text: "SWACHHAM. wilI collect personally identifiable information about you only as part of a voluntary registration process, online survey or any combination thereof. The Site may contain links to other Web sites. SWACHHAM. is not responsible for the privacy practices of such Web sites which it does not own, manage or control. The Site and third-party vendors, including Google, use first party cookies (such as the Google Analytics cookie) and third-party cookies (such as the DoubleClick cookie) together to inform, optimize, and serve ads based on someone's past visits to the Site." },
    { type: "heading", text: "WITH WHOM YOUR INFORMATION WILL BE SHARED?" },
    { type: "paragraph", text: "SWACHHAM. willI not use your financial information for any purpose other than to complete a transaction with you. SWACHHAM. does not rent, sell or share your personal information and will not disclose any of your personally identifiable information to third parties. In cases where it has your permission to provide products or services you've requested, and such information is necessary to provide these products or services the information may be shared with SWACHHAM.'s business associates and partners. SWACHHAM. may, however, share consumer information on an aggregate with its partners or third parties where it deems necessary. In addition, SWACHHAM. may use this information for promotional offers, to help investigate, prevent or take action regarding." },
  ],
};

/**
 * TERMS & CONDITIONS — the Terms of Service from the source document, through
 * Section 24, followed by the PRIVACY: and PROMOTIONS subsections that the
 * source places inside the same part.
 */
export const TERMS_AND_CONDITIONS: LegalDocument = {
  title: 'Terms & Conditions',
  blocks: [
    { type: "heading", text: "TERMS OF SERVICE" },
    { type: "paragraph", text: "This website (www.swachham.co.in) is owned and operated by swachham. Throughout the site, the terms \"we\", \"us\" and \"our\" refer to SWACHHAM. SWACHHAM. offers this website, including all information, tools and services available from this site to you, the user, conditioned upon your acceptance of all terms, conditions, policies and notices stated here." },
    { type: "paragraph", text: "By visiting our site, you engage in our \"Service\" and agree to be bound by the following terms and conditions (\"Terms of Service\", \"Terms\"), including those additional terms and conditions and policies referenced herein and/or available by hyperlink. These \"Terms of Service\" apply to all users of the site, including without limitation users who are browsers, vendors, customers, merchants, and/ or contributors of content." },
    { type: "paragraph", text: "Please read these \"Terms of Service\" carefully before accessing or using our website. By accessing or using any part of the site, you agree to be bound by these Terms of Service. If you do not agree to all the terms and conditions of this agreement, then you may not access the website or use any services. If these Terms of Service are considered an offer, acceptance is expressly limited to these Terms of Service." },
    { type: "paragraph", text: "Any new features or tools which are added to the current store shall also be subject to the Terms of Service. You can review the most current version of the Terms of Service at any time on this page. We reserve the right to update, change or replace any part of these Terms of Service by posting updates and/or changes to our website. It is your responsibility to check this page periodically for changes. Your continued use of or access to the website following the posting of any changes constitutes acceptance of those changes." },
    { type: "heading", text: "SECTION 1 WEBSITE USAGE TERMS" },
    { type: "paragraph", text: "By agreeing to these Terms of Service, you represent that you are at least the age of majority in your state or province of residence, or that you are the age of majority in your state or province of residence and you have given us your consent to allow any of your minor dependents to use this site. You may not use our products for any illegal or unauthorized purpose nor may you, in the use of the Service, violate any laws in your jurisdiction (including but not limited to copyright laws). You must not transmit any worms or viruses or any code of a destructive nature." },
    { type: "paragraph", text: "You are hereby authorized by SWACHHAM. to view, download, copy and print documents and the graphics incorporated therein (\"AUTHOR materials\") from this website subject to the following restrictions and in accordance with any written agreement between you and SWACHHAM.:" },
    { type: "paragraph", text: "The materials may be used solely by you for your own personal informational, educational or other non-commercial purposes unless otherwise expressly indicated;" },
    { type: "paragraph", text: "All copies you make must properly attribute the appropriate source, including any copyright or other proprietary notices originally shown or included in the materials;" },
    { type: "paragraph", text: "You may not modify any of the materials found at this website unless otherwise expressly indicated, nor attempt to pass off any materials found at this website as your own;" },
    { type: "paragraph", text: "You may not use, reproduce or publicly display or perform, or distribute any of the materials within this website for any commercial or public purpose, unless SWACHHAM. has given you prior written consent to do so;" },
    { type: "paragraph", text: "You may not \"mirror\" or \"frame\" any portions of this website in any other environment without prior written consent from SWACHHAM;" },
    { type: "paragraph", text: "You may not display or transmit SWACHHAM. RSS feed content in a manner that does not permit successful linking to, redirection to, or delivery of the applicable official SWACHHAM. URL (www.swachham.co.in), and you may not insert any intermediate page, splash page, or other content between the SWACHHAM. RSS link and the applicable official SWACHHAM. URL (www.swachham.co.in)." },
    { type: "paragraph", text: "SWACHHAM. reserves the right to terminate the access of any user in its sole discretion, including users that do not observe these Terms and Conditions or who infringe or otherwise violate the rights of others. You agree that you are expressly prohibited from using any materials found on this website to the detriment of SWACHHAM. or its affiliates in any type of patent infringement proceeding." },
    { type: "paragraph", text: "Your failure to comply with this prohibition constitutes copyright infringement of the materials at issue. Each instance of noncompliance with this prohibition constitutes a separate instance of infringement, and subjects you to a payment obligation as liquidated damages and not as a penalty. A breach or violation of any of the Terms will result in an immediate termination of our Services. You are prohibited from posting or transmitting to SWACHHAM. via this website, any material that is unlawful, obscene, pornographic, libellous, defamatory, threatening, or otherwise inappropriate" },
    { type: "heading", text: "SECTION 2 GENERAL CONDITIONS" },
    { type: "paragraph", text: "We reserve the right to refuse service to anyone for any reason at any time. You understand that your content may be transferred unencrypted and involve (a) transmissions over various networks; and (b) changes to conform and adapt to technical requirements of connecting networks or devices." },
    { type: "paragraph", text: "You agree not to reproduce, duplicate, copy, sell, resell or exploit any portion of the Service, use of the Service, or access to the Service or any contact on the website through which the service is provided, without express written permission by us." },
    { type: "paragraph", text: "Swaccham.co.in strives to provide the best quality service to its valuable customers. All the dry cleaning & laundry services provided by us here in India are based on standard practices followed by us. The services offered and techniques used have been tested and also adjusted to ensure optimum cleaning and safety of your everyday wear clothing in addition to the special fabrics & garments. In the event of damage caused in an article or loss for which we take the responsibility. The maximum compensation is limited to 3 times the service price, subject to a maximum of Rs 500 per garment. The garment for which the compensation is made shall be retained by the company." },
    { type: "paragraph", text: "After the pickup is done the consumer app will show the quantity picked up by the delivery person and is the final quantity we acknowledge as given by the customer. Any difference in the quantity shown in the app after pickup and the quantity delivered, we are responsible for it." },
    { type: "paragraph", text: "All garments received by us are photographed and inspected to check for stains and damages. We will share the details with the customer and process the garment only with the customer's consent." },
    { type: "paragraph", text: "In spite of the simple professional control carried out at the time of the reception of the articles, we cannot be held responsible for the damage due to non-identifiable properties or not detectable defects such as: insufficient resistance of fabrics or the seams, bad reaction of the colours or the impressions, presence of a pen in the lining, former defects, deterioration of the buttons, loops, zippers, shoulder pads, ornaments, etc., or if the label of maintenance is incorrect. A responsibility for contracting or modification of the colours remaining in the usual tolerances is excluded. The company aims to provide the best quality of cleaning available as per its standard methods; however, does not guarantee the removal of all stains on an article. Stain removal is a very complicated process and we do not guarantee stain removal in any case. Whenever possible, the company will notify the customer of stains and issues that cannot be resolved due to further possible damage to the fabric. The need for a particular treatment must be obvious especially in the event of delicate characteristics odf the textile easily recognizable of stains which require a special treatment. The symbol of maintenance and / or the indication of the care on the label of maintenance are determining for the cleaning of the textiles." },
    { type: "paragraph", text: "We commit ourselves to clean and provide additional services according to the professional methods. Your entrusted articles will be treated with the greatest care and respect for the environment. We welcome your feedback at all times and will ensure it is incorporated into our system for continuous improvement when possible." },
    { type: "paragraph", text: "The article(s) will be delivered as per the chosen delivery slot by the customer. Swachham will make 2 attempts to deliver the order as per customer request. Upon failure of delivery due to non-availability of the customer at the pre- designated address, Swachham cannot be held liable for loss of article(s) if customer fails to take delivery of the articles even after 2 attempts." },
    { type: "paragraph", text: "Any complaint(s) relating to the quality of service must be deposited without delay; and at the latest within 24 hours after receiving the article(s). Any complaints regarding shortfall of items in the order delivery need to be highlighted only at the time of delivery and before the order is marked delivered by the delivery executive. Once the customer has taken the delivery of the order and order is marked delivered Swachham will not entertain any complaints regarding the shortfall of the items. The right to entertain the complaint lies with the company in this case." },
    { type: "paragraph", text: "The complaints are carefully examined by our customer service and will be responded to with an explanation." },
    { type: "paragraph", text: "The general terms and conditions of this site are subject to the Indian Laws and Jurisdiction of Dapoli Courts only." },
    { type: "paragraph", text: "All taxes and levies applicable as per law." },
    { type: "paragraph", text: "We are not liable for any articles such as pen drive, keys, wallets, or other such items left in the clothes given. We will try our best to return them; however we do not guarantee them." },
    { type: "paragraph", text: "The headings used in this agreement are included for convenience only and will not limit or otherwise affect these terms." },
    { type: "heading", text: "SECTION 3 ACCURACY, COMPLETENESS AND TIMELINESS OF INFORMATION" },
    { type: "paragraph", text: "We are not responsible if information made available on this site is not accurate, complete or current. The material on this site is provided for general information only and should not be relied upon or used as the sole basis for making decisions without consulting primary, more accurate, more complete or timelier sources of information. Any reliance on the material on this site is at your own risk." },
    { type: "paragraph", text: "This site may contain certain historical information. Historical information, necessarily, is not current and is provided for your reference only. We reserve the right to modify the contents of this site at any time, but we have no obligation to update any information on our site. You agree that it is your responsibility to monitor changes to our site." },
    { type: "heading", text: "SECTION 4 MODIFICATIONS TO THE SERVICE AND PRICES" },
    { type: "paragraph", text: "Prices for our products are subject to change without notice. We reserve the right at any time to modify or discontinue the Service (or any part or content thereof) without notice at any time. We shall not be liable to you or to any third party for any modification, price change, suspension or discontinuance of the Service." },
    { type: "heading", text: "SECTION 5 PRODUCTS OR SERVICES" },
    { type: "paragraph", text: "Certain products or services may be available exclusively online through the website. These products or services may have limited quantities. We reserve the right, but are not obligated, to limit the sales of our products or services to any person, geographic region or jurisdiction. We may exercise this right on a case-by-case basis. We reserve the right to limit the quantities of any products or services that we offer. All descriptions of products or product pricing are subject to change at any time without notice, at the sole discretion of us. We reserve the right to discontinue any product at any time. Any offer for any product or service made on this site is void where prohibited." },
    { type: "heading", text: "SECTION 6 OPTIONAL TOOLS" },
    { type: "paragraph", text: "We may provide you with access to third party tools. You acknowledge and agree that we provide access to such tools \"as is\" and \"as available\" without any warranties, representations or conditions of any kind and without any endorsement. We shall have no liability whatsoever arising from or relating to your use of optional third-party tools." },
    { type: "paragraph", text: "Any use by you of optional tools offered through the site is entirely at your own risk and discretion and you should ensure that you are familiar with and approve of the terms on which tools are provided by the relevant third-party provider(s). We may also, in the future, offer new services and/or features through the website (including, the release of new tools and resources). Such new features and/or services shall also be subject to these Terms of Service." },
    { type: "heading", text: "SECTION 7 THIRD-PARTY LINKS" },
    { type: "paragraph", text: "Certain content, products and services available via our service may include materials from third parties. Third-party links on this site may direct you to third party websites that are not affiliated with us. We are not responsible for examining or evaluating the content or accuracy and we do not warrant and will not have any liability or responsibility for any third-party materials or websites, or for any other materials, products, or services of third parties." },
    { type: "paragraph", text: "We are not liable for any harm or damages related to the purchase or use of goods, services, resources, content, or any other transactions made in connection with any third-party websites. Please review carefully the third party's policies and practices and make sure you understand them before you engage in any transaction. Complaints, claims, concerns, or questions regarding third party products should be directed to the third party." },
    { type: "heading", text: "SECTION 8 USER COMMENTS, FEEDBACK AND OTHER SUBMISSIONS" },
    { type: "paragraph", text: "If, at our request, you send certain specific submissions (for example contest entries) or without a request from us you send creative ideas, suggestions, proposals, plans, or other materials, whether online, by email, by postal mail, or otherwise (collectively, 'comments'), you agree that we may, at any time, without restriction, edit, copy, publish, distribute, translate and otherwise use in any medium any comments that you forward to us. We are and shall be under no obligation (1) to maintain any comments in confidence; (2) to pay compensation for any comments; or (3) to respond to any comments." },
    { type: "paragraph", text: "We may, but have no obligation to, monitor, edit or remove content that we determine in our sole discretion are unlawful, offensive, threatening, libellous, defamatory, pornographic, obscene or otherwise objectionable or violates any party's intellectual property or these Terms of Service." },
    { type: "paragraph", text: "You agree that your comments will not violate any right of any third party, including copyright, trademark, privacy, personality or other personal or proprietary right. You further agree that your comments will not contain libellous or otherwise unlawful, abusive or obscene material, or contain any computer virus or other malware that could in any way affect the operation of the Service or any related website. You may not use a false email address, pretend to be someone other than yourself, or otherwise mislead us or third parties as to the origin of any comments. You are solely responsible for any comments you make and their accuracy. We take no responsibility and assume no liability for any comments posted by you or any third party" },
    { type: "heading", text: "SECTION 9 PERSONAL INFORMATION" },
    { type: "paragraph", text: "Your submission of personal information through the store is governed by our Privacy Policy" },
    { type: "heading", text: "SECTION 10 ERRORS, INACCURACIES AND OMISSIONS" },
    { type: "paragraph", text: "Occasionally there may be information on our site or in the Service that contains typographical errors, inaccuracies or omissions that may relate to product descriptions, pricing, promotions, offers, product shipping charges, transit times and availability. We reserve the right to correct any errors, inaccuracies or omissions, and to change or update information or cancel orders if any information in the Service or on any related website is inaccurate at any time without prior notice (including after you have submitted your order)." },
    { type: "paragraph", text: "We have a standard laundry turn-around time of 24 hours. In exceptional situations we may remove our laundry services for indefinite periods of time or cancel the services at any time due to unforeseen circumstances or events" },
    { type: "paragraph", text: "We undertake no obligation to update, amend or clarify information in the Service or on any related website, including without limitation, pricing information, except as required by law. No specified update or refresh date applied in the Service or on any related website, should be taken to indicate that all information in the Service or on any related website has been modified or updated." },
    { type: "heading", text: "SECTION 11 PROHIBITED USES" },
    { type: "paragraph", text: "In addition to other prohibitions as set forth in the Terms of Service, you are prohibited from using the site or its content: (a) for any unlawful purpose; (b) to solicit others to perform or participate in any unlawful acts; (c) to violate any international, federal, provincial or state regulations, rules, laws, or local ordinances; (d) to infringe upon or violate our intellectual property rights or the intellectual property rights of others; (e) to harass, abuse, insult, harm, defame, slander, disparage, intimidate, or discriminate based on gender, sexual orientation, religion, ethnicity, race, age, national origin, or disability; (f) to submit false or misleading information; (g) to upload or transmit viruses or any other type of malicious code that will or may be used in any way that will affect the functionality or operation of the Service or of any related website, other websites, or the Internet; (h) to collect or track the personal information of others; (i) to spam, phish, pharm, pretext, spider, crawl, or scrape; (j) for any obscene or immoral purpose; or (k) to interfere with or circumvent the security features of the Service or any related website, other websites, or the Internet. We reserve the right to terminate your use of the Service or any related website for violating any of the prohibited uses." },
    { type: "heading", text: "SECTION 12 DISCLAIMER OF WARRANTIES; LIMITATION OF LIABILITY" },
    { type: "paragraph", text: "We have a standard laundry turn-around time of 24 hours. In exceptional situations we may remove our laundry services for indefinite periods of time or cancel the services at any time due to unforeseen circumstances or events (natural or otherwise) outside our control, without an advance notice to you." },
    { type: "paragraph", text: "You expressly agree that your use of, or inability to use, the service is at your sole risk. The service and all products and services delivered to you through the service are (except as expressly stated by us) provided 'as is' and 'as available' for your use, without any representation, warranties or conditions of any kind, either express or implied, including all implied warranties or conditions of merchantability, merchantable quality, fitness for a particular purpose, durability, title, and no infringement." },
    { type: "paragraph", text: "In no case shall SWACHHAM., our directors, officers, employees, affiliates, agents, contractors, interns, suppliers, service providers or licensors be liable for any injury, loss, claim, or any direct, indirect, incidental, punitive, special, or consequential damages of any kind, including, without limitation lost profits, lost revenue, lost savings, loss of data, replacement costs, or any similar damages, whether based in contract, tort (including negligence), strict liability or otherwise, arising from your use of any of the service or any products procured using the service, or for any other claim related in any way to your use of the service or any product, including, but not limited to, any errors or omissions in any content, or any loss or damage of any kind incurred as a result of the use of the service or any content (or product) posted, transmitted, or otherwise made available via the service, even if advised of their possibility. Because some states or jurisdictions do not allow the exclusion or the limitation of liability for consequential or incidental damages, in such states or jurisdictions, our liability shall be limited to the maximum extent permitted by law." },
    { type: "heading", text: "SECTION 13 INDEMNIFICATION" },
    { type: "paragraph", text: "You agree to indemnify, defend and hold harmless SWACHHAM. and our parent, subsidiaries, affiliates, partners, officers, directors, agents, contractors, licensors, service providers, subcontractors, suppliers, interns and employees, harmless from any claim or demand, including reasonable attorneys' fees, made by any third party due to or arising out of your breach of these Terms of Service or the documents they incorporate by reference, or your violation of any law or the rights of a third party." },
    { type: "heading", text: "SECTION 14 SEVERABILITY" },
    { type: "paragraph", text: "In the event that any provision of these Terms of Service is determined to be unlawful, void or unenforceable, such provision shall nonetheless be enforceable to the fullest extent permitted by applicable law, and the unenforceable portion shall be deemed to be severed from these Terms of Service, such determination shall not affect the validity and enforceability of any other remaining provisions." },
    { type: "heading", text: "SECTION 15 TERMINATION" },
    { type: "paragraph", text: "The obligations and liabilities of the parties incurred prior to the termination date shall survive the termination of this agreement for all purposes." },
    { type: "paragraph", text: "These Terms of Service are effective unless and until terminated by either you or us. You may terminate these Terms of Service at any time by notifying us that you no longer wish to use our Services, or when you cease using our site." },
    { type: "paragraph", text: "If in our sole judgment you fail, or we suspect that you have failed, to comply with any term or provision of these Terms of Service, we also may terminate this agreement at any time without notice and you will remain liable for all amounts due up to and including the date of termination; and/or accordingly may deny you access to our Services (or any part thereof)." },
    { type: "heading", text: "SECTION 16 ENTIRE AGREEMENT" },
    { type: "paragraph", text: "The failure of us to exercise or enforce any right or provision of these Terms of Service shall not constitute a waiver of such right or provision. These Terms of Service and any policies or operating rules posted by us on this site or in respect to The Service constitutes the entire agreement and understanding between you and us and govern your use of the Service, superseding any prior or contemporaneous agreements, communications and proposals, whether oral or written, between you and us (including, but not limited to, any prior versions of the Terms of Service)." },
    { type: "paragraph", text: "Any ambiguities in the interpretation of these Terms of Service shall not be construed against" },
    { type: "heading", text: "SECTION 17 GOVERNING LAW" },
    { type: "paragraph", text: "These Terms of Service and any separate agreements whereby we provide you Services shall be governed by and construed in accordance with all laws under Indian Penal Code." },
    { type: "heading", text: "SECTION 18 CHANGES TO TERMS OF SERVICE" },
    { type: "paragraph", text: "You can review the most current version of the Terms of Service at any time at this page. We reserve the right, at our sole discretion, to update, change or replace any part of these Terms of Service by posting updates and changes to our website. It is your responsibility to check our website periodically for changes. Your continued use of or access to our website or the Service following the posting of any changes to these Terms of Service constitutes acceptance of those changes." },
    { type: "heading", text: "SECTION 19 TERMS FOR USING OUR SERVICE" },
    { type: "paragraph", text: "Clothes need to be counted at the time of delivery in front of the delivery guy and any discrepancy be notified at that time only." },
    { type: "paragraph", text: "Clothes will be handed over to security or friend or neighbour in case of customer not being available only when a written confirmation is provided from the customer in the form of a mail or text message." },
    { type: "paragraph", text: "The company will need minimum 2 day after the day of complaint to give an update on the issues raised." },
    { type: "paragraph", text: "The company tries to deliver clothes on time but sometimes due to unforeseeable circumstances there might be a delay in delivery." },
    { type: "paragraph", text: "Some stains are very tough and not covered under this service agreement. So, if the stains don't go, we will not be held responsible." },
    { type: "paragraph", text: "In case of damage to a cloth, the damage should be reported to the company within 48 hours of delivery." },
    { type: "paragraph", text: "In case of damage to a cloth, the company will try to rectify the damage. In case of failure in doing that, 3 times the amount of the service availed for, will be reimbursed. Please refer general conditions for more details." },
    { type: "paragraph", text: "We take special care in handling all types of cloths. But, due to the basic property of some clothes, they will bleed colours on their own. In such cases, company won't be liable for any loss. The company is not responsible if the customer forgets something in the clothes and it gets damaged and/or misplaced." },
    { type: "paragraph", text: "It is a strict policy of the company to not process damaged, torn, or stained clothes. It will be done only on special request and written approval (Either by mail or SMS ) by the customer." },
    { type: "heading", text: "SECTION 20 REFUND POLICY" },
    { type: "paragraph", text: "Swachham may provide partial/full refund in some cases We may also provide a complimentary rewash in some cases. The final decision for the same rests with Swachham management" },
    { type: "heading", text: "SECTION 21 CANCELLATION AND RESCHEDULING POLICY" },
    { type: "paragraph", text: "Customers can cancel at any time before actual pickup of their order(s). We charge a flat fee for cancelling an order pickup, if it is being done after the pickup cut off timing. This will be deducted from the customers' Swachham Wallet balance." },
    { type: "paragraph", text: "Customers can reschedule at any time before actual pickup and/or delivery of their order(s). We charge a flat fee for rescheduling an order pickup/delivery if it is being done after the pickup/delivery cut off timing. This fee will be deducted from the customers' Swachham Wallet balance." },
    { type: "heading", text: "SECTION 22 CONVENIENCE FEES" },
    { type: "paragraph", text: "Within the types of orders provided by Swachham, the 'Quick Order' option does not require you to select services and items from our catalogue. Customers can simply select a pickup and delivery date and book their laundry pickup. We charge a flat fee for placing an order through 'Quick Order' mode. This will be deducted from the customers' Swachham Wallet balance." },
    { type: "heading", text: "SECTION 23 DELIVERY CHARGES" },
    { type: "paragraph", text: "Delivery charges may be applied in the following scenarios:" },
    { type: "paragraph", text: "A) If the total service cost is below ₹500 excluding convenience or any other fees, delivery charges will apply. For orders classified as \"Quick Orders\" delivery charges will be assessed based on the total service cost, excluding convenience or any other fees, which is calculated prior to the processing of items." },
    { type: "paragraph", text: "B) If the application of a coupon reduces the total value of an order to below 500, delivery charges will be applied, regardless of the original order value prior to the coupon application." },
    { type: "heading", text: "SECTION 24 CONTACT INFORMATION" },
    { type: "paragraph", text: "Questions about the Terms of Service should be sent at info@swachham.co.in" },
    { type: "heading", text: "PRIVACY:" },
    { type: "paragraph", text: "SWACHHAM. respects your privacy. This Privacy Policy provides succinctly the manner your data is collected and used by SWACHHAM. on the Site. As a visitor to the Site/Customer you are advised to please read the Privacy Policy carefully. By accessing the services provided by the Site you agree to the collection and use of your data by SWACHHAM. in the manner provided in this Privacy Policy." },
    { type: "subheading", text: "WHAT INFORMATION IS, OR MAY BE, COLLECTED FORM YOU?" },
    { type: "paragraph", text: "As part of the registration process on the Site, SWACHHAM. may collect the following personally identifiable information about you: Name including first and last name, alternate email address, mobile phone number and contact details, Postal code, Demographic profile (like your age, gender, occupation, education, address etc.) and information about the pages on the site you visit/access, the links you click on the site, the number of times you access the page and any such browsing information." },
    { type: "subheading", text: "HOW DO WE COLLECT THE INFORMATION?" },
    { type: "paragraph", text: "SWACHHAM. will collect personally identifiable information about you only as part of a voluntary registration process, online survey or any combination thereof. The Site may contain links to other Web sites. SWACHHAM. is not responsible for the privacy practices of such Web sites which it does not own, manage or control. The Site and third-party vendors, including Google, use first party cookies (such as the Google Analytics cookie) and third-party cookies (such as the DoubleClick cookie) together to inform, optimize, and serve ads based on someone's past visits to the Site." },
    { type: "subheading", text: "HOW IS INFORMATION USED?" },
    { type: "paragraph", text: "SWACHHAM. will collect personally identifiable information about you only as part of a voluntary registration process, online survey or any combination thereof. The Site may contain links to other Web sites. SWACHHAM. is not responsible for the privacy practices of such Web sites which it does not own, manage or control. The Site and third-party vendors, including Google, use first party cookies (such as the Google Analytics cookie) and third-party cookies (such as the DoubleClick cookie) together to inform, optimize, and serve ads based on someone's past visits to the Site." },
    { type: "subheading", text: "WITH WHOM YOUR INFORMATION WILL BE SHARED?" },
    { type: "paragraph", text: "SWACHHAM. will not use your financial information for any purpose other than to complete a transaction with you. SWACHHAM. does not rent, sell or share your personal information and will not disclose any of your personally identifiable information to third parties. In cases where it has your permission to provide products or services you've requested, and such information is necessary to provide these products or services the information may be shared with SWACHHAM.'s business associates and partners. SWACHHAM. may, however, share consumer information on an aggregate with its partners or third parties where it deems necessary. In addition, SWACHHAM. may use this information for promotional offers, to help investigate, prevent or take action regarding unlawful and illegal activities, suspected fraud, potential threat to the safety or security of any person, violations of the Site's terms of use or to defend against legal claims; special circumstances such as compliance with subpoenas, court orders, requests/order from legal authorities or law enforcement agencies requiring such disclosure." },
    { type: "subheading", text: "WHAT CHOICE ARE AVAILABLE TO YOU REGARDING COLLECTION, USE AND DISTRIBUTION OF YOUR INFORMATION?" },
    { type: "paragraph", text: "To protect against the loss, misuse and alteration of the information under its control, SWACHHAM. has in place appropriate physical, electronic and managerial procedures. For example, SWACHHAM. servers are accessible only to authorized personnel and your information is shared with employees and authorised personnel on a need to know basis to complete the transaction annexed-to-know the services requested by you. Although SWACHHAM. will endeavour to safeguard the confidentiality of your personally identifiable information, transmissions made by means of the Internet cannot be made absolutely secure. By using this site, you agree that SWACHHAM. will have no liability for disclosure of your information due to errors in transmission or unauthorized acts of third parties." },
    { type: "subheading", text: "WHY IS LOCATION COLLECTED? HOW IS IT USED?" },
    { type: "paragraph", text: "We use Locus which is a routing algorithm for generating pickup & delivery routes for last mile delivery to the customers. These routes are then downloaded on our delivery app to do the deliveries and Locus SDK on the phone used by riders helps us track the location of the rider. Locus needs to know the path being followed by the rider. Location information of the rider will be used to send relevant updates to the end customer." },
    { type: "subheading", text: "HOW ARE YOUR LOCATION DETAILS COLLECTED?" },
    { type: "paragraph", text: "Your location details are collected using a third-party library or Google Play services based on configurations." },
    { type: "subheading", text: "HOW CAN YOU CORRECT INACCURACIES IN THE INFORMATION?" },
    { type: "paragraph", text: "To correct or update any information you have provided, the Site allows you to do it online. In the event of loss of access details, you can send an email to: info@swachham.co.in" },
    { type: "subheading", text: "POLICY UPDATES" },
    { type: "paragraph", text: "SWACHHAM. reserves the right to change or update this policy at any time. Such changes shall be effective immediately upon posting to the Site." },
    { type: "heading", text: "PROMOTIONS, OFFERS, DISCOUNTS AND COUPONS" },
    { type: "bullet", text: "Promotions, Offers, Discounts and Coupons are valid for a limited time only. SWACHHAM. (owners of the brand referred to hereon as \"SWACHHAM\") reserves the right to modify or cancel coupons at any time." },
    { type: "bullet", text: "If you do not purchase based on the qualifying items, services or order value, or percentage discount to your SWACHHAM Cart when the promotion, offer, discount or coupon is in effect, the discount will not apply." },
    { type: "bullet", text: "The coupon applies only to qualifying items, services or order value, or percentage discount displaying the promotion, offer, discount or coupon offer in your SWACHHAM Promos and on the item detail page." },
    { type: "bullet", text: "The promotion, offer, discount or coupon offer will not be valid until it is applied to the qualifying terms." },
    { type: "bullet", text: "The promotion, offer, discount or coupon may only be used on SWACHHAM Website swachham.co.in or SWACHHAM Android and iOS application, and in conjunction with the purchase of service offered by SWACHHAM and not on services sold by third-party sellers." },
    { type: "bullet", text: "The promotion, offer, discount or coupon is limited to one coupon per order." },
    { type: "bullet", text: "Promotion, offer, discount or coupon may not be combinable with multiple discounts or promotional rebates." },
    { type: "bullet", text: "Maximum discount applicable on coupons is INR 2,000" },
  ],
};

/** The documents the legal screen can render, addressed by route param. */
export const LEGAL_DOCUMENTS = {
  privacy: PRIVACY_POLICY,
  terms: TERMS_AND_CONDITIONS,
} as const;

export type LegalDocumentKey = keyof typeof LEGAL_DOCUMENTS;
